"""initial_schema_baseline

Revision ID: efdde5977741
Revises: 
Create Date: 2026-01-24 20:55:00.133465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdde5977741'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_approval_tasks_created_at', table_name='approval_tasks')
    op.drop_index('idx_approval_tasks_email_id', table_name='approval_tasks')
    op.drop_index('idx_approval_tasks_status', table_name='approval_tasks')
    op.drop_index('idx_auto_reply_rules_category', table_name='auto_reply_rules')
    op.drop_index('idx_auto_reply_rules_enabled', table_name='auto_reply_rules')
    op.alter_column('customers', 'customer_grade',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='客户分级: A=核心客户, B=重要客户, C=普通客户, D=潜在客户',
               existing_nullable=True)
    op.alter_column('customers', 'engagement_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='参与度评分 (0-100)',
               existing_nullable=True)
    op.alter_column('customers', 'response_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='邮件回复率 (0-1)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'lifetime_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='客户终身价值 CLV',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_customer_grade', table_name='customers')
    op.drop_index('idx_engagement_score', table_name='customers')
    op.drop_index('idx_last_active_date', table_name='customers')
    op.drop_index('idx_delivery_status', table_name='email_history')
    op.create_index(op.f('ix_email_history_delivery_status'), 'email_history', ['delivery_status'], unique=False)
    op.drop_column('email_history', 'questions_asked')
    op.drop_column('email_history', 'competition_status')
    op.drop_column('email_history', 'decision_authority')
    op.drop_column('email_history', 'communication_style')
    op.drop_column('email_history', 'risk_level')
    op.drop_column('email_history', 'business_impact')
    op.drop_column('email_history', 'conversion_probability')
    op.drop_column('email_history', 'mentioned_products')
    op.drop_column('email_history', 'customer_business_type')
    op.drop_column('email_history', 'mentioned_prices')
    op.drop_column('email_history', 'concerns')
    op.drop_column('email_history', 'mentioned_timeline')
    op.drop_column('email_history', 'risk_factors')
    op.drop_column('email_history', 'satisfaction_level')
    op.drop_column('email_history', 'mentioned_quantities')
    op.drop_column('email_history', 'secondary_category')
    op.drop_column('email_history', 'purchase_intent_score')
    op.drop_column('email_history', 'customer_grade_suggestion')
    op.drop_column('email_history', 'response_deadline')
    op.drop_column('email_history', 'full_analysis_json')
    op.drop_column('email_history', 'response_template_suggestion')
    op.drop_column('email_history', 'estimated_order_value')
    op.drop_column('email_history', 'professionalism')
    op.drop_column('email_history', 'human_review_reason')
    op.drop_column('email_history', 'opportunity_score')
    op.drop_column('email_history', 'budget_level')
    op.drop_column('email_history', 'requires_human_review')
    op.drop_column('email_history', 'tone')
    op.drop_index('idx_signatures_default', table_name='email_signatures')
    op.drop_index('idx_signatures_user', table_name='email_signatures')
    op.alter_column('prompt_templates', 'template_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='模板类型：reply(回复)/analysis(分析)/polish(润色)',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'system_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='系统级提示词，定义AI角色',
               existing_nullable=True)
    op.alter_column('prompt_templates', 'user_prompt_template',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='用户提示词模板，支持变量占位符',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'variables',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON格式的变量说明',
               existing_nullable=True)
    op.alter_column('prompt_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为默认模板（每种类型只能有一个默认）',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_prompt_templates_active', table_name='prompt_templates')
    op.drop_index('idx_prompt_templates_default', table_name='prompt_templates')
    op.drop_index('idx_prompt_templates_type', table_name='prompt_templates')
    op.drop_table_comment(
        'prompt_templates',
        existing_comment='AI提示词模板配置表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'prompt_templates',
        'AI提示词模板配置表',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_prompt_templates_type', 'prompt_templates', ['template_type'], unique=False)
    op.create_index('idx_prompt_templates_default', 'prompt_templates', ['is_default'], unique=False)
    op.create_index('idx_prompt_templates_active', 'prompt_templates', ['is_active'], unique=False)
    op.alter_column('prompt_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='是否为默认模板（每种类型只能有一个默认）',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_templates', 'variables',
               existing_type=sa.TEXT(),
               comment='JSON格式的变量说明',
               existing_nullable=True)
    op.alter_column('prompt_templates', 'user_prompt_template',
               existing_type=sa.TEXT(),
               comment='用户提示词模板，支持变量占位符',
               existing_nullable=False)
    op.alter_column('prompt_templates', 'system_prompt',
               existing_type=sa.TEXT(),
               comment='系统级提示词，定义AI角色',
               existing_nullable=True)
    op.alter_column('prompt_templates', 'template_type',
               existing_type=sa.VARCHAR(),
               comment='模板类型：reply(回复)/analysis(分析)/polish(润色)',
               existing_nullable=False)
    op.create_index('idx_signatures_user', 'email_signatures', ['user_id'], unique=False)
    op.create_index('idx_signatures_default', 'email_signatures', ['user_id', 'is_default'], unique=False)
    op.add_column('email_history', sa.Column('tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('requires_human_review', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('budget_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('opportunity_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('human_review_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('professionalism', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('estimated_order_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('response_template_suggestion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('full_analysis_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('response_deadline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('customer_grade_suggestion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('purchase_intent_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('secondary_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('mentioned_quantities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('satisfaction_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('risk_factors', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('mentioned_timeline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('concerns', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('mentioned_prices', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('customer_business_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('mentioned_products', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('conversion_probability', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('business_impact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('communication_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('decision_authority', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('competition_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('email_history', sa.Column('questions_asked', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_email_history_delivery_status'), table_name='email_history')
    op.create_index('idx_delivery_status', 'email_history', ['delivery_status'], unique=False)
    op.create_index('idx_last_active_date', 'customers', [sa.text('last_active_date DESC')], unique=False)
    op.create_index('idx_engagement_score', 'customers', [sa.text('engagement_score DESC')], unique=False)
    op.create_index('idx_customer_grade', 'customers', ['customer_grade'], unique=False)
    op.alter_column('customers', 'lifetime_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='客户终身价值 CLV',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'response_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='邮件回复率 (0-1)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'engagement_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='参与度评分 (0-100)',
               existing_nullable=True)
    op.alter_column('customers', 'customer_grade',
               existing_type=sa.VARCHAR(),
               comment='客户分级: A=核心客户, B=重要客户, C=普通客户, D=潜在客户',
               existing_nullable=True)
    op.create_index('idx_auto_reply_rules_enabled', 'auto_reply_rules', ['is_enabled'], unique=False)
    op.create_index('idx_auto_reply_rules_category', 'auto_reply_rules', ['email_category'], unique=False)
    op.create_index('idx_approval_tasks_status', 'approval_tasks', ['status'], unique=False)
    op.create_index('idx_approval_tasks_email_id', 'approval_tasks', ['email_id'], unique=False)
    op.create_index('idx_approval_tasks_created_at', 'approval_tasks', ['created_at'], unique=False)
    # ### end Alembic commands ###
